name: json_widget
description: Generate widgets from json
homepage: https://github.com/jonahwilliams/json_widget
author: Jonah Williams <jonahwilliams@google.com>
version: 0.1.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  build: ^1.1.4
  build_config: ^0.4.0
  dart_style: ^1.2.8

dev_dependencies:
  test: 1.6.4
